<?php

/**
 * This is the model base class for the table "produccion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Produccion".
 *
 * Columns in table "produccion" available as properties of the model,
 * followed by relations of table "produccion" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $estado
 * @property integer $escenario_id
 * @property integer $produccion_categoria_id
 *
 * @property Escenario $escenario
 * @property ProduccionCategoria $produccionCategoria
 * @property ProduccionMultimedia[] $produccionMultimedias
 */
abstract class BaseProduccion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'produccion';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, escenario_id, produccion_categoria_id', 'required'),
            array('escenario_id, produccion_categoria_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>150),
            array('estado', 'length', 'max'=>8),
            array('descripcion', 'safe'),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('descripcion, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, descripcion, estado, escenario_id, produccion_categoria_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'escenario' => array(self::BELONGS_TO, 'Escenario', 'escenario_id'),
            'produccionCategoria' => array(self::BELONGS_TO, 'ProduccionCategoria', 'produccion_categoria_id'),
            'produccionMultimedias' => array(self::HAS_MANY, 'ProduccionMultimedia', 'produccion_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'estado' => Yii::t('app', 'Estado'),
                'escenario_id' => Yii::t('app', 'Escenario'),
                'produccion_categoria_id' => Yii::t('app', 'Produccion Categoria'),
                'escenario' => null,
                'produccionCategoria' => null,
                'produccionMultimedias' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('escenario_id', $this->escenario_id);
        $criteria->compare('produccion_categoria_id', $this->produccion_categoria_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}