<?php

/**
 * This is the model base class for the table "proyecto_multimedia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProyectoMultimedia".
 *
 * Columns in table "proyecto_multimedia" available as properties of the model,
 * followed by relations of table "proyecto_multimedia" available as properties of the model.
 *
 * @property integer $id
 * @property string $ubicacion
 * @property integer $local
 * @property string $tipo
 * @property integer $menu
 * @property integer $encabezado
 * @property integer $proyecto_id
 *
 * @property Proyecto $proyecto
 */
abstract class BaseProyectoMultimedia extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'proyecto_multimedia';
    }

    public static function representingColumn() {
        return 'ubicacion';
    }

    public function rules() {
        return array(
            array('ubicacion, local, tipo, proyecto_id', 'required'),
            array('local, menu, encabezado, proyecto_id', 'numerical', 'integerOnly'=>true),
            array('tipo', 'length', 'max'=>45),
            array('menu, encabezado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, ubicacion, local, tipo, menu, encabezado, proyecto_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'proyecto' => array(self::BELONGS_TO, 'Proyecto', 'proyecto_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'ubicacion' => Yii::t('app', 'Ubicacion'),
                'local' => Yii::t('app', 'Local'),
                'tipo' => Yii::t('app', 'Tipo'),
                'menu' => Yii::t('app', 'Menu'),
                'encabezado' => Yii::t('app', 'Encabezado'),
                'proyecto_id' => Yii::t('app', 'Proyecto'),
                'proyecto' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('ubicacion', $this->ubicacion, true);
        $criteria->compare('local', $this->local);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('menu', $this->menu);
        $criteria->compare('encabezado', $this->encabezado);
        $criteria->compare('proyecto_id', $this->proyecto_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}