<?php

/**
 * This is the model base class for the table "evento_precio_taquilla".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventoPrecioTaquilla".
 *
 * Columns in table "evento_precio_taquilla" available as properties of the model,
 * followed by relations of table "evento_precio_taquilla" available as properties of the model.
 *
 * @property integer $id
 * @property double $precio
 * @property integer $cantidad
 * @property integer $evento_fecha_id
 * @property integer $escenario_taquilla_seccion_id
 *
 * @property EventoFecha $eventoFecha
 * @property EscenarioTaquillaSeccion $escenarioTaquillaSeccion
 */
abstract class BaseEventoPrecioTaquilla extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evento_precio_taquilla';
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('precio, cantidad, evento_fecha_id, escenario_taquilla_seccion_id', 'required'),
            array('cantidad, evento_fecha_id, escenario_taquilla_seccion_id', 'numerical', 'integerOnly'=>true),
            array('precio', 'numerical'),
            array('id, precio, cantidad, evento_fecha_id, escenario_taquilla_seccion_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'eventoFecha' => array(self::BELONGS_TO, 'EventoFecha', 'evento_fecha_id'),
            'escenarioTaquillaSeccion' => array(self::BELONGS_TO, 'EscenarioTaquillaSeccion', 'escenario_taquilla_seccion_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'precio' => Yii::t('app', 'Precio'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'evento_fecha_id' => Yii::t('app', 'Evento Fecha'),
                'escenario_taquilla_seccion_id' => Yii::t('app', 'Escenario Taquilla Seccion'),
                'eventoFecha' => null,
                'escenarioTaquillaSeccion' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('precio', $this->precio);
        $criteria->compare('cantidad', $this->cantidad);
        $criteria->compare('evento_fecha_id', $this->evento_fecha_id);
        $criteria->compare('escenario_taquilla_seccion_id', $this->escenario_taquilla_seccion_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}