<?php

/**
 * This is the model base class for the table "escenario_taquilla".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EscenarioTaquilla".
 *
 * Columns in table "escenario_taquilla" available as properties of the model,
 * followed by relations of table "escenario_taquilla" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $escenario_id
 *
 * @property Escenario $escenario
 * @property EscenarioTaquillaSeccion[] $escenarioTaquillaSeccions
 */
abstract class BaseEscenarioTaquilla extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'escenario_taquilla';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, escenario_id', 'required'),
            array('escenario_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('id, nombre, escenario_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'escenario' => array(self::BELONGS_TO, 'Escenario', 'escenario_id'),
            'escenarioTaquillaSeccions' => array(self::HAS_MANY, 'EscenarioTaquillaSeccion', 'escenario_taquilla_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'escenario_id' => Yii::t('app', 'Escenario'),
                'escenario' => null,
                'escenarioTaquillaSeccions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('escenario_id', $this->escenario_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}