<?php

/**
 * This is the model base class for the table "evento_autor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventoAutor".
 *
 * Columns in table "evento_autor" available as properties of the model,
 * followed by relations of table "evento_autor" available as properties of the model.
 *
 * @property integer $id
 * @property string $Nombre
 * @property string $descripcion
 * @property string $imagen
 *
 * @property Evento[] $eventos
 */
abstract class BaseEventoAutor extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evento_autor';
    }

    public static function representingColumn() {
        return 'Nombre';
    }

    public function rules() {
        return array(
            array('Nombre', 'required'),
            array('Nombre', 'length', 'max'=>100),
            array('descripcion, imagen', 'safe'),
            array('descripcion, imagen', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, Nombre, descripcion, imagen', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'eventos' => array(self::HAS_MANY, 'Evento', 'evento_autor_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'Nombre' => Yii::t('app', 'Nombre'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'imagen' => Yii::t('app', 'Imagen'),
                'eventos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('Nombre', $this->Nombre, true);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('imagen', $this->imagen, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}