<?php

/**
 * This is the model base class for the table "evento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Evento".
 *
 * Columns in table "evento" available as properties of the model,
 * followed by relations of table "evento" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $evento_autor_id
 * @property integer $evento_categoria_id
 * @property string $estado
 *
 * @property EventoAutor $eventoAutor
 * @property EventoCategoria $eventoCategoria
 * @property EventoFecha[] $eventoFechas
 * @property EventoMultimedia[] $eventoMultimedias
 */
abstract class BaseEvento extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evento';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, evento_autor_id, evento_categoria_id', 'required'),
            array('evento_autor_id, evento_categoria_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>100),
            array('estado', 'length', 'max'=>8),
            array('descripcion', 'safe'),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('descripcion, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, descripcion, evento_autor_id, evento_categoria_id, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'eventoAutor' => array(self::BELONGS_TO, 'EventoAutor', 'evento_autor_id'),
            'eventoCategoria' => array(self::BELONGS_TO, 'EventoCategoria', 'evento_categoria_id'),
            'eventoFechas' => array(self::HAS_MANY, 'EventoFecha', 'evento_id'),
            'eventoMultimedias' => array(self::HAS_MANY, 'EventoMultimedia', 'evento_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'evento_autor_id' => Yii::t('app', 'Evento Autor'),
                'evento_categoria_id' => Yii::t('app', 'Evento Categoria'),
                'estado' => Yii::t('app', 'Estado'),
                'eventoAutor' => null,
                'eventoCategoria' => null,
                'eventoFechas' => null,
                'eventoMultimedias' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('evento_autor_id', $this->evento_autor_id);
        $criteria->compare('evento_categoria_id', $this->evento_categoria_id);
        $criteria->compare('estado', $this->estado, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}